const esbuild = require("esbuild");
const process = require("process");
const fs = require("fs");
const path = require("path");
const esbuildSvelte = require("esbuild-svelte");
const sveltePreprocess = require("svelte-preprocess");

const banner =
    `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const dir = prod ? "./" : "./test-vault/.obsidian/plugins/obsidian-deepseek-plugin";

if (!prod && !fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
}

// Copy manifest for hot reload if not prod
if (!prod) {
    fs.copyFileSync("manifest.json", `${dir}/manifest.json`);
}

// Ensure the build finishes before copying production release files
esbuild.build({
    banner: { js: banner },
    entryPoints: ["src/main.ts"],
    bundle: true,
    plugins: [
        esbuildSvelte({
            compilerOptions: { css: 'injected' },
            preprocess: sveltePreprocess()
        })
    ],
    external: [
        "obsidian", "electron", "@codemirror/autocomplete", "@codemirror/collab",
        "@codemirror/commands", "@codemirror/language", "@codemirror/lint",
        "@codemirror/search", "@codemirror/state", "@codemirror/view",
        "@lezer/common", "@lezer/highlight", "@lezer/lr",
        ...Object.keys(require("./package.json").dependencies || {}),
        ...Object.keys(require("./package.json").peerDependencies || {}),
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: path.join(dir, "main.js"),
}).then(() => {
    // Post-build actions for release packaging
    if (prod) {
        const manifest = require('./manifest.json');
        const version = manifest.version;
        const releaseDir = `./releases/v${version}`;
        
        if (!fs.existsSync(releaseDir)) {
            fs.mkdirSync(releaseDir, { recursive: true });
        }
        
        fs.copyFileSync("main.js", path.join(releaseDir, "main.js"));
        fs.copyFileSync("manifest.json", path.join(releaseDir, "manifest.json"));
        if (fs.existsSync("styles.css")) {
            fs.copyFileSync("styles.css", path.join(releaseDir, "styles.css"));
        }
        console.log(`✅ Production build complete. Release files prepared in: ${releaseDir}/`);
    }
}).catch(() => process.exit(1));
