/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __publicField = (obj, key, value) => __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DeepSeekPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian7 = require("obsidian");

// src/view.ts
var import_obsidian = require("obsidian");
var DEEPSEEK_VIEW_TYPE = "deepseek-chat-view";
var DeepSeekView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    __publicField(this, "plugin");
    __publicField(this, "chatContainer");
    __publicField(this, "inputEl");
    __publicField(this, "messageHistory", []);
    __publicField(this, "lastSelection", "");
    __publicField(this, "isProcessing", false);
    __publicField(this, "stopRequested", false);
    __publicField(this, "stopBtn");
    __publicField(this, "toolCallDepth", 0);
    __publicField(this, "maxToolDepth", 10);
    this.plugin = plugin;
  }
  getViewType() {
    return DEEPSEEK_VIEW_TYPE;
  }
  getDisplayText() {
    return "AI Note Helper";
  }
  getIcon() {
    return "bot";
  }
  getAssistantName() {
    switch (this.plugin.settings.provider) {
      case "deepseek":
        return "DeepSeek";
      case "kimi":
        return "Kimi";
      case "openai":
        return "ChatGPT";
      default:
        return "Assistant";
    }
  }
  async onOpen() {
    await Promise.resolve();
    this.registerEvent(
      this.app.workspace.on("editor-change", (editor) => {
        const selection = editor.getSelection();
        if (selection) {
          this.lastSelection = selection;
        }
      })
    );
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("deepseek-chat-container");
    this.chatContainer = container.createDiv({ cls: "chat-messages" });
    const inputContainer = container.createDiv({ cls: "chat-input-container" });
    const actionBtnContainer = inputContainer.createDiv({ cls: "chat-action-btns" });
    this.stopBtn = actionBtnContainer.createEl("button", { text: "Stop", cls: "chat-stop-btn" });
    this.stopBtn.disabled = true;
    this.stopBtn.onclick = () => {
      this.stopRequested = true;
      this.stopBtn.disabled = true;
      this.stopBtn.innerText = "Stopping...";
      new import_obsidian.Notice("Stopping AI execution...");
    };
    const exportBtn = actionBtnContainer.createEl("button", { text: "Export Logs", cls: "chat-export-btn" });
    exportBtn.addEventListener("click", () => {
      void this.exportLogs().catch(console.error);
    });
    const clearBtn = actionBtnContainer.createEl("button", { text: "Clear Chat" });
    clearBtn.onclick = () => {
      this.messageHistory = [];
      this.chatContainer.empty();
      this.plugin.logger.clear();
      new import_obsidian.Notice("Chat and logs cleared.");
    };
    this.inputEl = inputContainer.createEl("textarea", { cls: "chat-input" });
    this.inputEl.placeholder = "Type your message... (Shift+enter for newline, Enter to send)";
    const sendBtn = inputContainer.createEl("button", { text: "Send" });
    sendBtn.addClass("mod-cta");
    sendBtn.addEventListener("click", () => {
      void this.handleSend().catch(console.error);
    });
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        void this.handleSend().catch(console.error);
      }
    });
    this.appendMessage("assistant", "Hello! Ask me anything. If you highlight text in your note, I will remember it and focus on that. I can also search your entire vault or update your note metadata if you ask me to!").catch(console.error);
  }
  async handleSend() {
    if (this.isProcessing) return;
    const instruction = this.inputEl.value.trim();
    if (!instruction) return;
    this.isProcessing = true;
    this.stopRequested = false;
    this.toolCallDepth = 0;
    this.stopBtn.disabled = false;
    this.stopBtn.innerText = "Stop";
    await this.appendMessage("user", instruction);
    this.plugin.logger.log("chat", "user", instruction);
    this.inputEl.value = "";
    let additionalContext = "";
    const links = instruction.match(/\[\[([^\]]+)\]\]/g);
    if (links) {
      additionalContext += "\n\n[CRITICAL CONTEXT: The following notes were mentioned. Use this content directly instead of searching.]\n";
      for (const link of links) {
        const path = link.slice(2, -2);
        const file = await this.resolveFile(path);
        if (file) {
          const content = await this.app.vault.read(file);
          additionalContext += `
--- Content of [[${file.basename}]] ---
${content}
`;
        }
      }
    }
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (activeView) {
      const currentSelection = activeView.editor.getSelection();
      if (currentSelection) {
        this.lastSelection = currentSelection;
      }
    }
    const activeFile = this.app.workspace.getActiveFile();
    let linkedNotesContext = "";
    if (activeFile) {
      const cache = this.app.metadataCache.getFileCache(activeFile);
      if (cache && cache.links) {
        const uniqueLinks = Array.from(new Set(cache.links.map((l) => l.link)));
        for (const linkPath of uniqueLinks) {
          const linkedFile = this.app.metadataCache.getFirstLinkpathDest(linkPath, activeFile.path);
          if (linkedFile instanceof import_obsidian.TFile && linkedFile.extension === "md") {
            const linkedContent = await this.app.vault.read(linkedFile);
            const truncatedContent = linkedContent.length > 1500 ? linkedContent.substring(0, 1500) + "... (truncated)" : linkedContent;
            linkedNotesContext += `
--- Linked Note: [[${linkedFile.basename}]] ---
${truncatedContent}
`;
          }
        }
      }
    }
    if (this.lastSelection && activeFile) {
      additionalContext += `

[System Info: The user highlighted the following text in the note "${activeFile.name}". Focus your answer specifically around this highlighted text:
---
${this.lastSelection}
---]`;
      this.lastSelection = "";
    } else if (activeFile) {
      const content = await this.app.vault.read(activeFile);
      additionalContext += `

[System Info: The user is currently viewing the note "${activeFile.name}". Its full content is:
---
${content}
---]`;
    }
    if (linkedNotesContext) {
      additionalContext += `

[System Info: The active note contains links to the following notes. Here is their content for additional context:
${linkedNotesContext}]`;
    }
    try {
      const finalPrompt = instruction + additionalContext;
      const messages = [
        { role: "system", content: "You are a helpful AI assistant integrated into Obsidian. You can converse naturally with the user. If they provide note context in [CRITICAL CONTEXT] blocks, ALWAYS check that context first before using any search or read tools to save time and tokens." }
      ];
      const recentHistory = this.messageHistory.slice(-10);
      recentHistory.forEach((msg) => messages.push(msg));
      messages.push({ role: "user", content: finalPrompt });
      await this.processConversationStream(messages, finalPrompt);
    } catch (error) {
      console.error("Deepseek error:", error);
      const errorMsg = error instanceof Error ? error.message : String(error);
      new import_obsidian.Notice("API error: " + errorMsg);
      await this.appendMessage("system", "Error: " + errorMsg);
    } finally {
      this.isProcessing = false;
      this.stopBtn.disabled = true;
      this.stopBtn.innerText = "Stop";
    }
  }
  /**
   * Specialized UI for Pipeline human-in-the-loop intervention.
   * Renders a card with an editable textarea and [Continue/Cancel] buttons.
   */
  async requestUserApproval(stepId, currentContent) {
    return new Promise((resolve) => {
      const msgDiv = this.chatContainer.createDiv({ cls: "chat-msg role-assistant pipeline-approval" });
      const headerDiv = msgDiv.createDiv({ cls: "msg-header" });
      headerDiv.createEl("strong", { text: `Pipeline Pause: ${stepId}`, cls: "chat-sender-label" });
      msgDiv.createEl("p", { text: "AI has generated the following. You can edit it before continuing:", cls: "pipeline-instruction" });
      const editArea = msgDiv.createEl("textarea", { cls: "chat-input pipeline-edit-area" });
      editArea.value = currentContent;
      editArea.rows = 5;
      const buttonContainer = msgDiv.createDiv({ cls: "pipeline-buttons" });
      const continueBtn = buttonContainer.createEl("button", { text: "\u2705 Continue", cls: "mod-cta" });
      const cancelBtn = buttonContainer.createEl("button", { text: "\u274C Cancel Pipeline" });
      continueBtn.onclick = () => {
        const finalValue = editArea.value;
        msgDiv.addClass("pipeline-resolved");
        continueBtn.disabled = true;
        cancelBtn.disabled = true;
        editArea.disabled = true;
        headerDiv.createEl("span", { text: " (Resumed)", cls: "pipeline-status" });
        resolve(finalValue);
      };
      cancelBtn.onclick = () => {
        msgDiv.addClass("pipeline-cancelled");
        continueBtn.disabled = true;
        cancelBtn.disabled = true;
        editArea.disabled = true;
        headerDiv.createEl("span", { text: " (Cancelled)", cls: "pipeline-status" });
        resolve(null);
      };
      this.chatContainer.scrollTop = this.chatContainer.scrollHeight;
    });
  }
  async appendMessage(role, text) {
    if (role !== "system" && role !== "tool") {
      this.messageHistory.push({ role, content: text });
      if (role === "assistant") {
        this.plugin.logger.log("chat", "assistant", text);
      }
    }
    const msgDiv = this.chatContainer.createDiv({ cls: `chat-msg role-${role}` });
    const assistantName = this.getAssistantName();
    const senderName = role === "user" ? "You" : role === "assistant" ? assistantName : role === "tool" ? "Tool" : "System";
    const headerDiv = msgDiv.createDiv({ cls: "msg-header" });
    headerDiv.createEl("strong", {
      text: senderName,
      cls: "chat-sender-label"
    });
    if (role === "assistant") {
      const copyBtn = headerDiv.createEl("button", {
        text: "Copy",
        cls: "clickable-icon chat-copy-btn"
      });
      copyBtn.addEventListener("click", () => {
        void (async () => {
          await navigator.clipboard.writeText(text);
          copyBtn.innerText = "Copied!";
          setTimeout(() => {
            copyBtn.innerText = "Copy";
          }, 2e3);
        })().catch(console.error);
      });
    }
    const contentDiv = msgDiv.createDiv({ cls: "msg-content" });
    if (role === "user" || role === "system" || role === "tool") {
      contentDiv.addClass("chat-whitespace-pre");
      contentDiv.innerText = text;
      msgDiv.addClass(role === "user" ? "chat-msg-user" : "chat-msg-system");
    } else {
      msgDiv.addClass("chat-msg-assistant");
      await import_obsidian.MarkdownRenderer.render(this.app, text, contentDiv, "", this);
    }
    this.chatContainer.scrollTo(0, this.chatContainer.scrollHeight);
  }
  async executeReadNote(path) {
    const file = await this.resolveFile(path);
    if (!file) return `Error: Note "${path}" not found. Try searching for it first.`;
    const content = await this.app.vault.read(file);
    return `Full content of [[${file.basename}]] (Path: ${file.path}):

${content}`;
  }
  async resolveFile(pathStr) {
    var _a;
    let file = this.app.vault.getAbstractFileByPath(pathStr);
    if (file instanceof import_obsidian.TFile) return file;
    if (!pathStr.endsWith(".md")) {
      file = this.app.vault.getAbstractFileByPath(pathStr + ".md");
      if (file instanceof import_obsidian.TFile) return file;
    }
    const basename = ((_a = pathStr.split("/").pop()) == null ? void 0 : _a.replace(".md", "")) || pathStr;
    const allFiles = this.app.vault.getMarkdownFiles();
    const found = allFiles.find((f) => f.basename.toLowerCase() === basename.toLowerCase());
    return found || null;
  }
  async executeSearchVault(query) {
    const files = this.app.vault.getMarkdownFiles();
    const results = [];
    const lowerQuery = query.toLowerCase();
    const logDir = (this.plugin.settings.logDirectory || "DeepSeek-Logs").toLowerCase();
    const skillsDir = (this.plugin.settings.skillsDirectory || "DeepSeek-Skills").toLowerCase();
    let filteredFiles = files.filter((file) => {
      const path = file.path.toLowerCase();
      if (path.includes(logDir)) return false;
      if (path.includes(skillsDir)) return false;
      return true;
    });
    const exactMatches = filteredFiles.filter((f) => f.basename.toLowerCase() === lowerQuery);
    filteredFiles.sort((a, b) => b.stat.mtime - a.stat.mtime);
    const sortedFiles = [...exactMatches, ...filteredFiles.filter((f) => !exactMatches.includes(f))];
    for (const file of sortedFiles) {
      const content = await this.app.vault.cachedRead(file);
      const contentLower = content.toLowerCase();
      const nameLower = file.basename.toLowerCase();
      const pathLower = file.path.toLowerCase();
      if (contentLower.includes(lowerQuery) || nameLower.includes(lowerQuery) || pathLower.includes(lowerQuery)) {
        const isExactMatch = nameLower === lowerQuery;
        const matchIndex = contentLower.includes(lowerQuery) ? contentLower.indexOf(lowerQuery) : 0;
        const start = Math.max(0, matchIndex - 60);
        const end = Math.min(content.length, matchIndex + 140);
        if (isExactMatch) {
          const fullOrLarge = content.length < 3e3 ? content : content.substring(0, 3e3) + "... (truncated, use read_note for full)";
          results.push(`--- EXACT MATCH: [[${file.basename}]] (Path: ${file.path}) ---
Full/Large snippet content:
${fullOrLarge}
`);
        } else {
          results.push(`--- File: [[${file.basename}]] (Path: ${file.path}) ---
...${content.substring(start, end)}
`);
        }
        if (results.length >= 5) break;
      }
    }
    if (results.length === 0) return `No files found matching "${query}".`;
    return `Search results for "${query}" (Excluding logs/skills):

` + results.join("\n");
  }
  async executeUpdateMetadata(properties) {
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) return "Error: No active file to update.";
    try {
      await this.app.fileManager.processFrontMatter(activeFile, (frontmatter) => {
        for (const [key, value] of Object.entries(properties)) {
          frontmatter[key] = value;
        }
      });
      return `Successfully updated metadata for ${activeFile.basename}.`;
    } catch (e) {
      return `Failed to update metadata: ${e instanceof Error ? e.message : String(e)}`;
    }
  }
  async executeCreateNote(path, content) {
    try {
      if (!path.endsWith(".md")) path += ".md";
      const normalizedPath = path.replace(/^\//, "");
      const fileExists = this.app.vault.getAbstractFileByPath(normalizedPath);
      if (fileExists) {
        return `Error: File already exists at path ${normalizedPath}`;
      }
      await this.app.vault.create(normalizedPath, content);
      return `Successfully created new note at ${normalizedPath}`;
    } catch (e) {
      return `Failed to create note: ${e instanceof Error ? e.message : String(e)}`;
    }
  }
  async executeAppendToNote(path, content) {
    try {
      if (!path.endsWith(".md")) path += ".md";
      const file = await this.resolveFile(path);
      if (!file) {
        return `Error: Markdown file not found for "${path}". Try searching for it first if you're unsure of the path.`;
      }
      await this.app.vault.append(file, "\n" + content);
      return `Successfully appended content to ${file.path}`;
    } catch (e) {
      return `Failed to append to note: ${e instanceof Error ? e.message : String(e)}`;
    }
  }
  async executeModifyDirectory(directoryPath, instruction) {
    await Promise.resolve();
    try {
      const normalizedPath = directoryPath.replace(/^\//, "").replace(/\/$/, "");
      const folder = normalizedPath === "" ? this.app.vault.getRoot() : this.app.vault.getAbstractFileByPath(normalizedPath);
      if (!folder) {
        return `Error: Directory not found at path ${normalizedPath || "/"}`;
      }
      const markdownFiles = [];
      const getFiles = (f) => {
        if (f instanceof import_obsidian.TFolder) {
          for (const child of f.children) {
            getFiles(child);
          }
        } else if (f instanceof import_obsidian.TFile && f.extension === "md") {
          markdownFiles.push(f);
        }
      };
      getFiles(folder);
      if (markdownFiles.length === 0) {
        return `No markdown files found in directory ${normalizedPath || "/"}`;
      }
      const filePaths = markdownFiles.map((f) => f.path).join(", ");
      return `Found ${markdownFiles.length} files in directory ${normalizedPath || "/"}. The files are: ${filePaths}. 
To apply the instruction "${instruction}", please call 'update_metadata' or 'append_to_note' on these files one by one.`;
    } catch (e) {
      return `Failed to process directory: ${e instanceof Error ? e.message : String(e)}`;
    }
  }
  async processConversationStream(messages, originalUserPrompt) {
    if (this.stopRequested) {
      await this.appendMessage("system", "Execution stopped by user.");
      return;
    }
    if (this.toolCallDepth >= this.maxToolDepth) {
      await this.appendMessage("system", "Error: Maximum tool call depth reached. Stopping to prevent infinite loop.");
      return;
    }
    const { provider, apiKeys, apiUrl, model } = this.plugin.settings;
    const apiKey = apiKeys[provider];
    if (!apiKey) {
      throw new Error(`API Key not set for provider ${provider}.`);
    }
    const tools = [
      {
        type: "function",
        function: {
          name: "read_note",
          description: "Reads the full content of a specific markdown note. Use this when you have a file path and need to summarize or fully understand its content.",
          parameters: {
            type: "object",
            properties: {
              path: { type: "string", description: "The path or name of the note to read (e.g. 'Daily/2026-03-16.md' or 'Note Name')" }
            },
            required: ["path"]
          }
        }
      },
      {
        type: "function",
        function: {
          name: "search_vault",
          description: "Search the entire Obsidian vault for files matching a keyword query. Use this when the user asks about past files, vault contents, or broader knowledge outside the current note.",
          parameters: {
            type: "object",
            properties: {
              query: { type: "string", description: "The keyword or phrase to search for." }
            },
            required: ["query"]
          }
        }
      },
      {
        type: "function",
        function: {
          name: "update_metadata",
          description: "Update the YAML frontmatter / metadata of the active note. Use this if the user asks you to add tags, change status, or edit properties.",
          parameters: {
            type: "object",
            properties: {
              properties: {
                type: "object",
                description: "Key-value pairs to set in the frontmatter. For tags, use an array of strings."
              }
            },
            required: ["properties"]
          }
        }
      },
      {
        type: "function",
        function: {
          name: "create_note",
          description: "Create a new markdown note in the vault at the specified path.",
          parameters: {
            type: "object",
            properties: {
              path: { type: "string", description: "The path including filename where the note should be created, e.g. 'Daily/2026-01-01.md'." },
              content: { type: "string", description: "The initial markdown content of the new note." }
            },
            required: ["path", "content"]
          }
        }
      },
      {
        type: "function",
        function: {
          name: "append_to_note",
          description: "Append new content to the end of an existing note.",
          parameters: {
            type: "object",
            properties: {
              path: { type: "string", description: "The path of the existing note, e.g. 'Ideas/Project.md'." },
              content: { type: "string", description: "The content to append to the end of the note." }
            },
            required: ["path", "content"]
          }
        }
      },
      {
        type: "function",
        function: {
          name: "modify_files_in_directory",
          description: "Get a list of all markdown files in a directory to perform bulk operations.",
          parameters: {
            type: "object",
            properties: {
              directory_path: { type: "string", description: "The path of the directory to scan, e.g. 'Work/Projects'. Use '/' for the root vault." },
              instruction: { type: "string", description: "A description of what needs to be changed across these files." }
            },
            required: ["directory_path", "instruction"]
          }
        }
      }
    ];
    const msgDiv = this.chatContainer.createDiv({ cls: `chat-msg role-assistant` });
    msgDiv.addClass("chat-msg-assistant");
    const assistantName = this.getAssistantName();
    const headerDiv = msgDiv.createDiv({ cls: "msg-header" });
    const senderLabel = headerDiv.createEl("strong", {
      text: `${assistantName} (thinking...)`,
      cls: "chat-sender-label"
    });
    const copyBtn = headerDiv.createEl("button", {
      text: "Copy",
      cls: "clickable-icon chat-copy-btn chat-hidden"
    });
    const contentDiv = msgDiv.createDiv({ cls: "msg-content" });
    try {
      const requestBody = {
        model,
        messages,
        stream: false,
        tools
      };
      let finalUrl = apiUrl || "https://api.deepseek.com/v1/chat/completions";
      if (apiUrl && !apiUrl.endsWith("/chat/completions")) {
        finalUrl = apiUrl.endsWith("/") ? `${apiUrl}chat/completions` : `${apiUrl}/chat/completions`;
      }
      const response = await (0, import_obsidian.requestUrl)({
        url: finalUrl,
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${apiKey}`
        },
        body: JSON.stringify(requestBody)
      });
      if (this.stopRequested) {
        await this.appendMessage("system", "Execution stopped by user.");
        return;
      }
      const data = response.json;
      const resMsg = data.choices[0].message;
      const fullResponse = resMsg.content || "";
      const toolCalls = resMsg.tool_calls || [];
      if (toolCalls.length > 0) {
        senderLabel.innerText = `${assistantName} (running ${toolCalls.length} tools...)`;
        messages.push(resMsg);
        const toolPromises = toolCalls.map(async (tc) => {
          const name = tc.function.name;
          const args = JSON.parse(tc.function.arguments || "{}");
          let result = "";
          try {
            if (name === "read_note") result = await this.executeReadNote(args.path);
            else if (name === "search_vault") result = await this.executeSearchVault(args.query);
            else if (name === "update_metadata") result = await this.executeUpdateMetadata(args.properties);
            else if (name === "create_note") result = await this.executeCreateNote(args.path, args.content);
            else if (name === "append_to_note") result = await this.executeAppendToNote(args.path, args.content);
            else if (name === "modify_files_in_directory") result = await this.executeModifyDirectory(args.directory_path, args.instruction);
            else result = `Error: Unknown tool ${name}`;
            this.plugin.logger.log("tool", "tool", `Executed ${name}`, { arguments: args, result });
          } catch (e) {
            result = `Error executing tool: ${e instanceof Error ? e.message : String(e)}`;
            this.plugin.logger.log("tool", "tool", `Failed to execute ${name}`, { arguments: tc.function.arguments, error: result });
          }
          return { id: tc.id, name, result };
        });
        const results = await Promise.all(toolPromises);
        for (const res of results) {
          messages.push({
            role: "tool",
            tool_call_id: res.id,
            name: res.name,
            content: res.result
          });
        }
        msgDiv.addClass("chat-msg-tool");
        contentDiv.innerText = `=> Used tools: ${results.map((r) => r.name).join(", ")}
=> Last result snippet: ${results[results.length - 1].result.substring(0, 100)}...`;
        this.toolCallDepth++;
        await this.processConversationStream(messages, originalUserPrompt);
        return;
      }
      senderLabel.innerText = assistantName;
      copyBtn.removeClass("chat-hidden");
      copyBtn.addEventListener("click", () => {
        void (async () => {
          await navigator.clipboard.writeText(fullResponse);
          copyBtn.innerText = "Copied!";
          setTimeout(() => {
            copyBtn.innerText = "Copy";
          }, 2e3);
        })().catch(console.error);
      });
      contentDiv.innerHTML = "";
      await import_obsidian.MarkdownRenderer.render(this.app, fullResponse, contentDiv, "", this);
      if (originalUserPrompt) {
        const cleanPrompt = originalUserPrompt.split("\n\n[System Info")[0];
        if (this.messageHistory.length === 0 || this.messageHistory[this.messageHistory.length - 1].content !== cleanPrompt) {
          this.messageHistory.push({ role: "user", content: cleanPrompt });
        }
      }
      this.messageHistory.push({ role: "assistant", content: fullResponse });
    } catch (e) {
      msgDiv.remove();
      throw e;
    }
  }
  async exportLogs() {
    const md = this.plugin.logger.getMarkdown();
    const timestamp = (/* @__PURE__ */ new Date()).toISOString().replace(/[:.]/g, "-");
    const fileName = `Execution-Log-${timestamp}.md`;
    const logDir = this.plugin.settings.logDirectory || "DeepSeek-Logs";
    const folder = this.app.vault.getAbstractFileByPath(logDir);
    if (!folder) {
      await this.app.vault.createFolder(logDir);
    } else if (!(folder instanceof import_obsidian.TFolder)) {
      new import_obsidian.Notice(`Error: ${logDir} already exists as a file. Please change the log directory in settings.`);
      return;
    }
    const path = `${logDir}/${fileName}`;
    try {
      await this.app.vault.create(path, md);
      new import_obsidian.Notice(`Logs exported to ${path}`);
      const file = this.app.vault.getAbstractFileByPath(path);
      if (file instanceof import_obsidian.TFile) {
        await this.app.workspace.getLeaf().openFile(file);
      }
    } catch (e) {
      console.error("Failed to export logs:", e);
      new import_obsidian.Notice("Failed to export logs: " + (e instanceof Error ? e.message : String(e)));
    }
  }
};

// src/logger.ts
var ExecutionLogger = class {
  constructor() {
    __publicField(this, "logs", []);
  }
  log(type, role, content, data) {
    const entry = {
      timestamp: (/* @__PURE__ */ new Date()).toISOString(),
      type,
      role,
      content,
      data
    };
    this.logs.push(entry);
    console.log(`[DeepSeek Log] ${role.toUpperCase()}: ${content.substring(0, 100)}${content.length > 100 ? "..." : ""}`);
  }
  clear() {
    this.logs = [];
  }
  getLogs() {
    return [...this.logs];
  }
  getMarkdown() {
    let md = `# DeepSeek Note Helper Execution Logs

`;
    md += `Generated at: ${(/* @__PURE__ */ new Date()).toLocaleString()}

`;
    md += `---

`;
    for (const log of this.logs) {
      md += `### [${log.timestamp}] ${log.role.toUpperCase()} (${log.type.toUpperCase()})
`;
      md += `${log.content}

`;
      if (log.data) {
        md += `**Data:**
\`\`\`json
${JSON.stringify(log.data, null, 2)}
\`\`\`

`;
      }
      md += `---

`;
    }
    return md;
  }
};

// src/skillManager.ts
var import_obsidian4 = require("obsidian");

// src/skillExecutor.ts
var import_obsidian3 = require("obsidian");

// src/llmService.ts
var import_obsidian2 = require("obsidian");
var LlmService = class {
  constructor(plugin) {
    __publicField(this, "plugin");
    this.plugin = plugin;
  }
  /**
   * Executes a headless AI request and returns the string response.
   * Ideal for pipeline processing where we don't want to pollute the chat UI.
   */
  async ask(prompt) {
    var _a;
    const { provider, apiKeys, apiUrl, model } = this.plugin.settings;
    const apiKey = apiKeys[provider];
    if (!apiKey) {
      throw new Error(`API Key not set for provider ${provider}.`);
    }
    const messages = [{ role: "user", content: prompt }];
    let endpoint = apiUrl.endsWith("/") ? `${apiUrl}chat/completions` : `${apiUrl}/chat/completions`;
    const payload = {
      model,
      messages,
      temperature: 0.7,
      max_tokens: 4e3
    };
    const headers = {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${apiKey}`
    };
    try {
      this.plugin.logger.log("api", "system", `Sending request to ${provider}`, { model, messages });
      const response = await (0, import_obsidian2.requestUrl)({
        url: endpoint,
        method: "POST",
        headers,
        body: JSON.stringify(payload)
      });
      const leaves = this.plugin.app.workspace.getLeavesOfType("deepseek-chat-view");
      const view = (_a = leaves[0]) == null ? void 0 : _a.view;
      if (view && view.stopRequested) {
        this.plugin.logger.log("api", "system", "Request returned but stop was requested. Aborting.");
        throw new Error("STOPPED_BY_USER");
      }
      if (response.status !== 200) {
        const errorText = `API returned status ${response.status}: ${response.text}`;
        this.plugin.logger.log("api", "system", `API error: ${errorText}`);
        throw new Error(errorText);
      }
      const data = response.json;
      if (data && data.choices && data.choices.length > 0 && data.choices[0].message) {
        const content = data.choices[0].message.content;
        this.plugin.logger.log("api", "assistant", `Received response from ${provider}`, { content });
        return content;
      } else {
        throw new Error("Unexpected API response format");
      }
    } catch (error) {
      console.error("Headless LLM request failed:", error);
      this.plugin.logger.log("api", "system", `Request failed: ${error instanceof Error ? error.message : String(error)}`);
      throw error;
    }
  }
  /**
   * Executes a streaming AI request.
   */
  async streamAsk(prompt, onUpdate, signal) {
    var _a, _b, _c;
    const { provider, apiKeys, apiUrl, model } = this.plugin.settings;
    const apiKey = apiKeys[provider];
    if (!apiKey) {
      throw new Error(`API Key not set for provider ${provider}.`);
    }
    let endpoint = apiUrl.endsWith("/") ? `${apiUrl}chat/completions` : `${apiUrl}/chat/completions`;
    const payload = {
      model,
      messages: [{ role: "user", content: prompt }],
      temperature: 0.7,
      stream: true
    };
    try {
      this.plugin.logger.log("api", "system", `Starting stream request to ${provider}`, { model });
      const response = await fetch(endpoint, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${apiKey}`
        },
        body: JSON.stringify(payload),
        signal
      });
      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`API error ${response.status}: ${errorText}`);
      }
      const reader = (_a = response.body) == null ? void 0 : _a.getReader();
      if (!reader) throw new Error("Response body is null");
      const decoder = new TextDecoder();
      let fullText = "";
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        const chunk = decoder.decode(value, { stream: true });
        const lines = chunk.split("\n");
        for (const line of lines) {
          const trimmed = line.trim();
          if (!trimmed || !trimmed.startsWith("data: ")) continue;
          const dataStr = trimmed.slice(6);
          if (dataStr === "[DONE]") break;
          try {
            const data = JSON.parse(dataStr);
            const content = ((_c = (_b = data.choices[0]) == null ? void 0 : _b.delta) == null ? void 0 : _c.content) || "";
            if (content) {
              fullText += content;
              onUpdate(fullText);
            }
          } catch (e) {
          }
        }
      }
      this.plugin.logger.log("api", "assistant", `Stream complete from ${provider}`);
      return fullText;
    } catch (error) {
      if (error instanceof Error && error.name === "AbortError") {
        this.plugin.logger.log("api", "system", "Stream request aborted by user");
        throw error;
      }
      console.error("Streaming LLM request failed:", error);
      this.plugin.logger.log("api", "system", `Stream failed: ${error instanceof Error ? error.message : String(error)}`);
      throw error;
    }
  }
};

// src/skillExecutor.ts
var SkillExecutor = class {
  constructor(app, plugin) {
    __publicField(this, "plugin");
    __publicField(this, "app");
    __publicField(this, "llm");
    this.app = app;
    this.plugin = plugin;
    this.llm = new LlmService(plugin);
  }
  async execute(skill) {
    this.plugin.logger.log("pipeline", "system", `Starting execution of skill: ${skill.name}`, { skill });
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
    const activeFile = this.app.workspace.getActiveFile();
    const initialContext = {
      selection: activeView ? activeView.editor.getSelection() : "",
      title: activeFile ? activeFile.basename : "",
      content: activeFile ? await this.app.vault.cachedRead(activeFile) : ""
    };
    try {
      initialContext.clipboard = await navigator.clipboard.readText();
    } catch (e) {
      console.log("Failed to read clipboard:", e);
      initialContext.clipboard = "";
    }
    if (skill.mode === "pipeline" && skill.steps) {
      await this.executePipeline(skill, initialContext, activeView);
    } else {
      let prompt = this.renderTemplate(skill.template, initialContext);
      if (skill.action === "to_chat") {
        await this.executeToChat(prompt);
      } else if (skill.action === "replace") {
        await this.executeReplace(prompt, activeView);
      } else if (skill.action === "insert_below") {
        await this.executeInsert(prompt, activeView);
      } else {
        console.log(`Action ${skill.action} is not yet implemented.`);
      }
    }
  }
  renderTemplate(template, context) {
    let rendered = template;
    rendered = rendered.replace(/\{\{date:([^}]+)\}\}/g, (_, fmt) => {
      const now = /* @__PURE__ */ new Date();
      return fmt.replace("YYYY", now.getFullYear().toString()).replace("MM", String(now.getMonth() + 1).padStart(2, "0")).replace("DD", String(now.getDate()).padStart(2, "0")).replace("HH", String(now.getHours()).padStart(2, "0")).replace("mm", String(now.getMinutes()).padStart(2, "0")).replace("ss", String(now.getSeconds()).padStart(2, "0"));
    });
    for (const [key, value] of Object.entries(context)) {
      const regex = new RegExp(`\\{\\{${key}\\}\\}`, "g");
      rendered = rendered.replace(regex, value);
    }
    return rendered;
  }
  async executePipeline(skill, initialContext, activeView) {
    var _a, _b, _c;
    const pipelineContext = { ...initialContext };
    const totalSteps = ((_a = skill.steps) == null ? void 0 : _a.length) || 0;
    new import_obsidian3.Notice(`Starting pipeline: ${skill.name} (${totalSteps} steps)`);
    for (let i = 0; i < totalSteps; i++) {
      const view = (_b = this.app.workspace.getLeavesOfType(DEEPSEEK_VIEW_TYPE)[0]) == null ? void 0 : _b.view;
      if (view && view.stopRequested) {
        new import_obsidian3.Notice("Pipeline stopped by user.");
        this.plugin.logger.log("pipeline", "system", "Pipeline aborted by stop request.");
        return;
      }
      const step = skill.steps[i];
      const renderedPrompt = this.renderTemplate(step.prompt, pipelineContext);
      this.plugin.logger.log("pipeline", "system", `Executing step: ${step.id}`, { stepId: step.id, action: step.action, prompt: renderedPrompt });
      let stepResult = "";
      if (step.action === "process") {
        stepResult = await this.llm.ask(renderedPrompt);
      } else if (step.action === "to_chat") {
        await this.executeToChat(renderedPrompt);
        stepResult = "[Sent to Chat]";
      } else if (step.action === "replace") {
        await this.executeReplace(renderedPrompt, activeView);
        stepResult = "[Replaced in Editor]";
      } else if (step.action === "ask_user") {
        await this.plugin.activateView();
        await new Promise((resolve) => setTimeout(resolve, 100));
        const view2 = (_c = this.app.workspace.getLeavesOfType(DEEPSEEK_VIEW_TYPE)[0]) == null ? void 0 : _c.view;
        if (view2) {
          const approved = await view2.requestUserApproval(step.id, renderedPrompt);
          if (approved === null) {
            new import_obsidian3.Notice("Pipeline canceled.");
            return;
          }
          stepResult = approved;
        } else {
          new import_obsidian3.Notice("Error: Side panel not found.");
          return;
        }
      } else if (step.action === "insert_below") {
        const currentView = activeView || this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
        await this.executeInsert(renderedPrompt, currentView);
        stepResult = "[Inserted in Editor]";
      } else if (step.action === "replace") {
        const currentView = activeView || this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
        await this.executeReplace(renderedPrompt, currentView);
        stepResult = "[Replaced in Editor]";
      } else {
        console.warn(`Unknown action ${step.action} in step ${step.id}`);
      }
      pipelineContext[step.id] = stepResult;
      this.plugin.logger.log("pipeline", "system", `Step ${step.id} completed`, { result: stepResult });
    }
    new import_obsidian3.Notice(`Pipeline "${skill.name}" completed.`);
  }
  async executeToChat(prompt) {
    await this.plugin.activateView();
    await new Promise((resolve) => setTimeout(resolve, 50));
    const leaves = this.app.workspace.getLeavesOfType("deepseek-chat-view");
    if (leaves.length > 0) {
      const view = leaves[0].view;
      if (view && view.inputEl) {
        view.inputEl.value = prompt;
        if (typeof view.handleSend === "function") {
          void view.handleSend().catch(console.error);
        }
      }
    }
  }
  async executeReplace(prompt, activeView) {
    if (!activeView) {
      new import_obsidian3.Notice("No active markdown view found for replace action.");
      return;
    }
    const editor = activeView.editor;
    new import_obsidian3.Notice("AI is thinking (replace)...", 3e3);
    try {
      const aiResponse = await this.llm.ask(prompt);
      editor.replaceSelection(aiResponse);
      new import_obsidian3.Notice("Content replaced.");
    } catch (error) {
      console.error("Replace LLM execution failed:", error);
      new import_obsidian3.Notice("AI request failed. Check console or API key.");
    }
  }
  async executeInsert(prompt, activeView) {
    if (!activeView) {
      new import_obsidian3.Notice("No active markdown view found for insert action.");
      return;
    }
    const editor = activeView.editor;
    new import_obsidian3.Notice("AI is thinking (insert)...", 3e3);
    try {
      const aiResponse = await this.llm.ask(prompt);
      const cursor = editor.getCursor();
      const textToInsert = `
${aiResponse}
`;
      const lineStr = editor.getLine(cursor.line);
      editor.replaceRange(textToInsert, { line: cursor.line, ch: lineStr.length });
      new import_obsidian3.Notice("Content inserted.");
    } catch (error) {
      console.error("Insert LLM execution failed:", error);
      new import_obsidian3.Notice("AI request failed. Check console or API key.");
    }
  }
};

// src/skillManager.ts
var SkillManager = class {
  constructor(app, plugin) {
    __publicField(this, "plugin");
    __publicField(this, "app");
    __publicField(this, "executor");
    __publicField(this, "skills", /* @__PURE__ */ new Map());
    __publicField(this, "registeredCommands", /* @__PURE__ */ new Set());
    this.app = app;
    this.plugin = plugin;
    this.executor = new SkillExecutor(app, plugin);
  }
  async loadSkills() {
    const skillsDir = this.plugin.settings.skillsDirectory;
    if (!skillsDir) return;
    const targetDir = skillsDir.endsWith("/") ? skillsDir : skillsDir + "/";
    const targetDirLower = targetDir.toLowerCase();
    const files = this.app.vault.getMarkdownFiles();
    for (const file of files) {
      const filePathLower = file.path.toLowerCase();
      if (filePathLower.startsWith(targetDirLower)) {
        await this.loadSkillFromFile(file);
      }
    }
    this.registerWatchers(skillsDir);
  }
  registerWatchers(skillsDir) {
    const skillsDirLower = skillsDir.toLowerCase();
    this.plugin.registerEvent(
      this.app.vault.on("modify", async (file) => {
        if (file instanceof import_obsidian4.TFile && file.path.toLowerCase().startsWith(skillsDirLower) && file.extension === "md") {
          await this.loadSkillFromFile(file);
        }
      })
    );
    this.plugin.registerEvent(
      this.app.vault.on("create", async (file) => {
        if (file instanceof import_obsidian4.TFile && file.path.toLowerCase().startsWith(skillsDirLower) && file.extension === "md") {
          await this.loadSkillFromFile(file);
        }
      })
    );
    this.plugin.registerEvent(
      this.app.vault.on("delete", (file) => {
        if (file.path.toLowerCase().startsWith(skillsDirLower)) {
          this.removeSkill(file.path);
        }
      })
    );
  }
  async loadSkillFromFile(file) {
    try {
      const content = await this.app.vault.read(file);
      const match = content.match(/^\s*---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);
      if (!match) {
        console.log(`Failed to load skill: No valid YAML frontmatter found in ${file.path}`);
        return;
      }
      const yamlString = match[1];
      const template = match[2].trim();
      let frontmatter;
      try {
        frontmatter = (0, import_obsidian4.parseYaml)(yamlString);
      } catch (e) {
        console.error(`Failed to parse YAML in ${file.path}:`, e);
        return;
      }
      if (!frontmatter || !frontmatter.name) {
        console.log(`Failed to load skill: Missing 'name' in ${file.path}`);
        return;
      }
      if (frontmatter.mode !== "pipeline" && !frontmatter.action) {
        console.log(`Failed to load skill: Missing 'action' in ${file.path}`);
        return;
      }
      let steps = void 0;
      if (frontmatter.mode === "pipeline") {
        steps = this.parsePipelineSteps(template);
      }
      const skill = {
        id: file.path,
        name: frontmatter.name,
        action: frontmatter.action || "pipeline",
        mode: frontmatter.mode,
        steps,
        icon: frontmatter.icon || "bot",
        template
      };
      this.skills.set(skill.id, skill);
      this.registerCommandForSkill(skill);
    } catch (e) {
      console.error(`Failed to load skill from ${file.path}:`, e);
    }
  }
  parsePipelineSteps(content) {
    const steps = [];
    const stepBlocks = content.split(/^\[STEP:\s*(.+?)\]\s*$/m);
    for (let i = 1; i < stepBlocks.length; i += 2) {
      const id = stepBlocks[i].trim();
      const blockContent = stepBlocks[i + 1].trim();
      const actionMatch = blockContent.match(/^action:\s*(.+)$/m);
      const action = actionMatch ? actionMatch[1].trim() : "process";
      let prompt = blockContent;
      if (actionMatch) {
        prompt = blockContent.replace(actionMatch[0], "").trim();
      }
      steps.push({
        id,
        action,
        prompt
      });
    }
    return steps;
  }
  removeSkill(filePath) {
    this.skills.delete(filePath);
  }
  registerCommandForSkill(skill) {
    const commandId = `skill-${skill.id}`;
    this.plugin.addCommand({
      id: commandId,
      name: `Skill: ${skill.name}`,
      icon: skill.icon,
      callback: () => {
        void this.executor.execute(skill).catch(console.error);
      }
    });
    this.registeredCommands.add(commandId);
  }
};

// src/hoverView.ts
var import_obsidian5 = require("obsidian");
var DeepSeekHoverView = class {
  constructor(app, plugin) {
    __publicField(this, "app");
    __publicField(this, "plugin");
    __publicField(this, "containerEl");
    __publicField(this, "inputEl");
    __publicField(this, "resultEl");
    __publicField(this, "contextEl");
    __publicField(this, "copyBtn");
    __publicField(this, "llmService");
    __publicField(this, "selection", "");
    __publicField(this, "abortController", null);
    __publicField(this, "isVisible", false);
    this.app = app;
    this.plugin = plugin;
    this.llmService = new LlmService(plugin);
    this.containerEl = document.createElement("div");
    this.containerEl.addClass("deepseek-hover-container");
    this.containerEl.style.display = "none";
    document.body.appendChild(this.containerEl);
    const dragHandle = this.containerEl.createDiv({ cls: "deepseek-hover-drag-handle" });
    dragHandle.createDiv({ cls: "deepseek-hover-drag-pill" });
    this.setupDragging(dragHandle);
    const resultWrapper = this.containerEl.createDiv({ cls: "deepseek-hover-result-wrapper" });
    this.resultEl = resultWrapper.createDiv({ cls: "deepseek-hover-result" });
    this.copyBtn = resultWrapper.createEl("button", { cls: "deepseek-hover-copy-btn" });
    this.copyBtn.innerHTML = `<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg>`;
    this.copyBtn.title = "Copy";
    this.copyBtn.style.display = "none";
    this.copyBtn.onclick = async () => {
      if (!this.resultEl.innerText) return;
      await navigator.clipboard.writeText(this.resultEl.innerText);
      const originalHTML = this.copyBtn.innerHTML;
      this.copyBtn.innerHTML = `<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg>`;
      setTimeout(() => this.copyBtn.innerHTML = originalHTML, 2e3);
    };
    const footerWrapper = this.containerEl.createDiv({ cls: "chat-footer-wrapper" });
    this.contextEl = footerWrapper.createDiv({ cls: "deepseek-hover-context" });
    this.contextEl.style.display = "none";
    const inputContainer = footerWrapper.createDiv({ cls: "deepseek-hover-input-wrapper" });
    this.inputEl = inputContainer.createEl("textarea", { cls: "deepseek-hover-input" });
    this.inputEl.placeholder = "Ask AI about selection...";
    this.inputEl.rows = 1;
    const hintIcons = inputContainer.createDiv({ cls: "deepseek-hover-hint-icons" });
    hintIcons.innerHTML = `<span class="deepseek-key-icon">\u21B5</span><span class="deepseek-key-icon">esc</span>`;
    const helperText = footerWrapper.createDiv({ cls: "deepseek-hover-helper-text" });
    helperText.innerText = "Enter to send \u2022 Esc to close";
    this.inputEl.addEventListener("input", () => {
      this.inputEl.style.height = "auto";
      this.inputEl.style.height = this.inputEl.scrollHeight + "px";
    });
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        void this.handleSubmit();
      } else if (e.key === "Escape") {
        this.hide();
      }
    });
    document.addEventListener("mousedown", (e) => {
      if (this.isVisible && !this.containerEl.contains(e.target)) {
        this.hide();
      }
    });
  }
  setupDragging(handle) {
    let isDragging = false;
    let startX = 0, startY = 0, initialLeft = 0, initialTop = 0;
    handle.addEventListener("mousedown", (e) => {
      if (e.target.tagName.toLowerCase() === "button") return;
      isDragging = true;
      startX = e.clientX;
      startY = e.clientY;
      initialLeft = this.containerEl.offsetLeft;
      initialTop = this.containerEl.offsetTop;
      document.addEventListener("mousemove", onMouseMove);
      document.addEventListener("mouseup", onMouseUp);
    });
    const onMouseMove = (e) => {
      if (!isDragging) return;
      const dx = e.clientX - startX;
      const dy = e.clientY - startY;
      this.containerEl.style.left = `${initialLeft + dx}px`;
      this.containerEl.style.top = `${initialTop + dy}px`;
    };
    const onMouseUp = () => {
      isDragging = false;
      document.removeEventListener("mousemove", onMouseMove);
      document.removeEventListener("mouseup", onMouseUp);
    };
  }
  async show(editor, selection) {
    var _a, _b;
    this.selection = selection;
    this.isVisible = true;
    this.containerEl.style.display = "flex";
    this.resultEl.empty();
    this.inputEl.value = "";
    this.inputEl.style.height = "auto";
    if (selection) {
      this.contextEl.innerText = selection;
      this.contextEl.style.display = "block";
      (_a = this.contextEl.parentElement) == null ? void 0 : _a.classList.add("has-context");
    } else {
      this.contextEl.style.display = "none";
      (_b = this.contextEl.parentElement) == null ? void 0 : _b.classList.remove("has-context");
    }
    const targetWidth = window.innerWidth * 0.4;
    const targetHeight = window.innerHeight * 0.95;
    this.containerEl.style.width = `${targetWidth}px`;
    this.containerEl.style.height = `${targetHeight}px`;
    const top = (window.innerHeight - targetHeight) / 2;
    const left = 20;
    this.containerEl.style.top = `${top}px`;
    this.containerEl.style.left = `${left}px`;
    this.inputEl.focus();
  }
  hide() {
    if (this.abortController) {
      this.abortController.abort();
      this.abortController = null;
    }
    this.containerEl.style.display = "none";
    this.isVisible = false;
  }
  async handleSubmit() {
    const prompt = this.inputEl.value.trim();
    if (!prompt) return;
    this.copyBtn.style.display = "none";
    this.inputEl.disabled = true;
    this.inputEl.placeholder = "AI is thinking...";
    this.resultEl.empty();
    this.resultEl.addClass("deepseek-is-loading");
    this.abortController = new AbortController();
    try {
      const fullPrompt = `Context Selection:
"""
${this.selection}
"""

User Question: ${prompt}`;
      let accumulatedText = "";
      await this.llmService.streamAsk(
        fullPrompt,
        async (text) => {
          accumulatedText = text;
          this.resultEl.empty();
          await import_obsidian5.MarkdownRenderer.render(this.app, accumulatedText, this.resultEl, "", this.plugin);
          this.resultEl.scrollTop = this.resultEl.scrollHeight;
        },
        this.abortController.signal
      );
    } catch (error) {
      if (error instanceof Error && error.name === "AbortError") {
      } else {
        new import_obsidian5.Notice("AI Request failed: " + (error instanceof Error ? error.message : String(error)));
        this.resultEl.createEl("p", { text: "Error: " + (error instanceof Error ? error.message : String(error)), cls: "deepseek-error" });
      }
    } finally {
      this.inputEl.disabled = false;
      this.inputEl.placeholder = "Ask AI about selection...";
      this.inputEl.value = "";
      this.inputEl.style.height = "auto";
      this.resultEl.removeClass("deepseek-is-loading");
      this.copyBtn.style.display = "block";
      this.abortController = null;
      this.inputEl.focus();
    }
  }
};

// src/main.ts
var import_obsidian8 = require("obsidian");

// src/telegramService.ts
var import_obsidian6 = require("obsidian");
var TelegramService = class {
  constructor(plugin) {
    __publicField(this, "plugin");
    __publicField(this, "intervalId", null);
    __publicField(this, "llmService");
    __publicField(this, "isFetching", false);
    this.plugin = plugin;
    this.llmService = new LlmService(plugin);
  }
  startPolling() {
    this.stopPolling();
    const interval = this.plugin.settings.tgPollingInterval || 60;
    this.plugin.logger.log("system", "system", `Starting Telegram polling every ${interval} seconds`);
    void this.fetchUpdates();
    this.intervalId = window.setInterval(() => {
      void this.fetchUpdates();
    }, interval * 1e3);
  }
  stopPolling() {
    if (this.intervalId) {
      window.clearInterval(this.intervalId);
      this.intervalId = null;
      this.plugin.logger.log("system", "system", "Stopped Telegram polling");
    }
  }
  async fetchUpdates() {
    if (this.isFetching) return;
    const { tgBotToken, tgChatId, tgLastUpdateId } = this.plugin.settings;
    if (!tgBotToken || !tgChatId) return;
    this.isFetching = true;
    try {
      const offset = tgLastUpdateId + 1;
      const url = `https://api.telegram.org/bot${tgBotToken}/getUpdates?offset=${offset}`;
      const response = await (0, import_obsidian6.requestUrl)({ url, method: "GET" });
      if (response.status !== 200) {
        throw new Error(`Telegram API returned ${response.status}`);
      }
      const data = response.json;
      if (data.ok && data.result && data.result.length > 0) {
        let maxUpdateId = tgLastUpdateId;
        for (const update of data.result) {
          try {
            await this.processUpdate(update);
          } catch (e) {
            console.error("Error processing individual update:", e);
            this.plugin.logger.log("system", "system", `Error processing update ${update.update_id}: ${e.message || String(e)}`);
          }
          if (update.update_id > maxUpdateId) {
            maxUpdateId = update.update_id;
          }
        }
        if (maxUpdateId > tgLastUpdateId) {
          this.plugin.settings.tgLastUpdateId = maxUpdateId;
          await this.plugin.saveSettings();
          this.plugin.logger.log("system", "system", `Updated Telegram lastUpdateId to ${maxUpdateId} and saved settings.`);
        }
      }
    } catch (error) {
      console.error("Failed to fetch Telegram updates:", error);
      this.plugin.logger.log("system", "system", `Telegram fetch failed: ${error instanceof Error ? error.message : String(error)}`);
    } finally {
      this.isFetching = false;
    }
  }
  async processUpdate(update) {
    const { tgChatId } = this.plugin.settings;
    const message = update.message;
    if (!message) return;
    if (String(message.chat.id) !== String(tgChatId)) {
      this.plugin.logger.log("system", "system", `Ignored message from unauthorized Chat ID: ${message.chat.id}`);
      return;
    }
    const text = message.text;
    if (text) {
      await this.handleMessage(text);
    }
  }
  async handleMessage(text) {
    let finalContent = text;
    const { tgAiProcessing, tgPromptTemplate, tgSavePath } = this.plugin.settings;
    if (tgAiProcessing) {
      try {
        const prompt = tgPromptTemplate.replace("{{tg_message}}", text);
        this.plugin.logger.log("system", "system", "Processing Telegram message with AI...");
        finalContent = await this.llmService.ask(prompt);
      } catch (error) {
        console.error("AI Processing failed for TG message:", error);
        this.plugin.logger.log("system", "system", `AI processing failed, falling back to original. Error: ${error instanceof Error ? error.message : String(error)}`);
        finalContent = `[AI \u5904\u7406\u5931\u8D25] ${text}`;
      }
    }
    await this.appendToVault(tgSavePath, finalContent);
  }
  async appendToVault(path, content) {
    const { vault } = this.plugin.app;
    const timestamp = (/* @__PURE__ */ new Date()).toLocaleString();
    const formattedEntry = `

--- 
### \u{1F4C5} ${timestamp}
${content}
`;
    try {
      let file = vault.getAbstractFileByPath(path);
      if (file instanceof import_obsidian6.TFile) {
        await vault.process(file, (data) => data + formattedEntry);
      } else {
        const pathParts = path.split("/");
        if (pathParts.length > 1) {
          const dirPath = pathParts.slice(0, -1).join("/");
          if (!vault.getAbstractFileByPath(dirPath)) {
            await vault.createFolder(dirPath);
          }
        }
        await vault.create(path, `# Telegram Notes
${formattedEntry}`);
      }
      new import_obsidian6.Notice(`Telegram message captured to ${path}`);
      this.plugin.logger.log("system", "system", `Appended Telegram message to ${path}`);
    } catch (error) {
      console.error("Failed to append message to vault:", error);
      this.plugin.logger.log("system", "system", `Failed to append to vault: ${error instanceof Error ? error.message : String(error)}`);
      new import_obsidian6.Notice(`Failed to save Telegram message: ${error instanceof Error ? error.message : String(error)}`);
    }
  }
};

// src/main.ts
var DEFAULT_SETTINGS = {
  provider: "deepseek",
  apiKey: "",
  apiKeys: {
    "deepseek": "",
    "kimi": "",
    "openai": "",
    "custom": ""
  },
  apiUrl: "https://api.deepseek.com",
  model: "deepseek-chat",
  skillsDirectory: "DeepSeek-Skills",
  logDirectory: "DeepSeek-Logs",
  tgBotToken: "",
  tgChatId: "",
  tgPollingInterval: 60,
  tgSavePath: "Telegram-Notes.md",
  tgAiProcessing: true,
  tgPromptTemplate: "\u4F60\u662F\u4E00\u4E2A\u77E5\u8BC6\u5E93\u52A9\u624B\u3002\u4EE5\u4E0B\u662F\u7528\u6237\u5728\u6237\u5916\u901A\u8FC7\u624B\u673A\u3010\u8BED\u97F3\u8F6C\u6587\u5B57\u3011\u53D1\u6765\u7684\u788E\u7247\u8BB0\u5F55\uFF0C\u53EF\u80FD\u5305\u542B\u540C\u97F3\u9519\u522B\u5B57\u548C\u4E2D\u82F1\u5939\u6742\u9519\u8BEF\u3002\u8BF7\u4FEE\u590D\u9519\u8BEF\u3001\u53BB\u9664\u53E3\u8BED\u5E9F\u8BDD\uFF0C\u5E76\u63D0\u70BC\u4E3A\u7ED3\u6784\u6E05\u6670\u7684 Markdown \u683C\u5F0F\uFF08\u53EF\u9002\u5EA6\u52A0\u7C97\u6216\u5217\u70B9\uFF09\u3002\u53EA\u8FD4\u56DE\u5904\u7406\u540E\u7684\u5185\u5BB9\uFF0C\u4E0D\u8981\u56DE\u590D\u5176\u4ED6\u5E9F\u8BDD\u3002\u539F\u6587\uFF1A\n{{tg_message}}",
  tgLastUpdateId: 0
};
var DeepSeekPlugin = class extends import_obsidian7.Plugin {
  constructor() {
    super(...arguments);
    __publicField(this, "settings", DEFAULT_SETTINGS);
    __publicField(this, "skillManager");
    __publicField(this, "logger", new ExecutionLogger());
    __publicField(this, "telegramService");
    __publicField(this, "hoverView");
  }
  async onload() {
    await this.loadSettings();
    this.registerView(
      DEEPSEEK_VIEW_TYPE,
      (leaf) => new DeepSeekView(leaf, this)
    );
    this.addRibbonIcon("bot", "Open deepseek helper", () => {
      void this.activateView().catch(console.error);
    });
    this.addSettingTab(new DeepSeekSettingTab(this.app, this));
    this.skillManager = new SkillManager(this.app, this);
    this.app.workspace.onLayoutReady(() => {
      void this.skillManager.loadSkills().catch(console.error);
    });
    this.hoverView = new DeepSeekHoverView(this.app, this);
    this.addCommand({
      id: "deepseek-hover-ai",
      name: "Hover AI Chat",
      editorCallback: (editor) => {
        const selection = editor.getSelection();
        this.hoverView.show(editor, selection);
      },
      hotkeys: [
        {
          modifiers: ["Mod", "Shift"],
          key: "j"
        }
      ]
    });
    this.telegramService = new TelegramService(this);
    this.startPolling();
  }
  startPolling() {
    if (this.telegramService) {
      this.telegramService.startPolling();
    }
  }
  onunload() {
    if (this.telegramService) {
      this.telegramService.stopPolling();
    }
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(DEEPSEEK_VIEW_TYPE);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({ type: DEEPSEEK_VIEW_TYPE, active: true });
      }
    }
    if (leaf) {
      void workspace.revealLeaf(leaf);
    }
  }
  async loadSettings() {
    const loadedData = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, loadedData);
    if (!this.settings.apiKeys) {
      this.settings.apiKeys = { ...DEFAULT_SETTINGS.apiKeys };
    }
    if (this.settings.apiKey && !this.settings.apiKeys["deepseek"]) {
      this.settings.apiKeys["deepseek"] = this.settings.apiKey;
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var DeepSeekSettingTab = class extends import_obsidian8.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    __publicField(this, "plugin");
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian8.Setting(containerEl).setName("Deepseek").setHeading();
    new import_obsidian8.Setting(containerEl).setName("AI Provider").setDesc("Select the AI service provider.").addDropdown((drop) => drop.addOption("deepseek", "DeepSeek").addOption("kimi", "Kimi (Moonshot)").addOption("openai", "OpenAI").addOption("custom", "Custom").setValue(this.plugin.settings.provider).onChange(async (value) => {
      this.plugin.settings.provider = value;
      if (value === "deepseek") {
        this.plugin.settings.apiUrl = "https://api.deepseek.com";
        this.plugin.settings.model = "deepseek-chat";
      } else if (value === "kimi") {
        this.plugin.settings.apiUrl = "https://api.moonshot.cn/v1";
        this.plugin.settings.model = "moonshot-v1-8k";
      } else if (value === "openai") {
        this.plugin.settings.apiUrl = "https://api.openai.com/v1";
        this.plugin.settings.model = "gpt-4o-mini";
      }
      await this.plugin.saveSettings();
      this.display();
    }));
    new import_obsidian8.Setting(containerEl).setName("API key").setDesc(`Enter your API key for ${this.plugin.settings.provider}.`).addText((text) => text.setValue(this.plugin.settings.apiKeys[this.plugin.settings.provider] || "").onChange((value) => {
      this.plugin.settings.apiKeys[this.plugin.settings.provider] = value;
      if (this.plugin.settings.provider === "deepseek") {
        this.plugin.settings.apiKey = value;
      }
      void this.plugin.saveSettings().catch(console.error);
    }));
    new import_obsidian8.Setting(containerEl).setName("API URL").setDesc("Endpoint for the API. (Will auto-update if Provider is changed)").addText((text) => text.setValue(this.plugin.settings.apiUrl).onChange((value) => {
      this.plugin.settings.apiUrl = value;
      void this.plugin.saveSettings().catch(console.error);
    }));
    new import_obsidian8.Setting(containerEl).setName("Model").setDesc("Model to use.").addText((text) => text.setValue(this.plugin.settings.model).onChange((value) => {
      this.plugin.settings.model = value;
      void this.plugin.saveSettings().catch(console.error);
    }));
    new import_obsidian8.Setting(containerEl).setName("Skills directory").setDesc("Folder where your Markdown skills are stored (e.g. DeepSeek-Skills).").addText((text) => text.setValue(this.plugin.settings.skillsDirectory).onChange((value) => {
      this.plugin.settings.skillsDirectory = value;
      void this.plugin.skillManager.loadSkills().catch(console.error);
    }));
    new import_obsidian8.Setting(containerEl).setName("Log export directory").setDesc("Folder where execution logs will be exported (e.g. DeepSeek-Logs).").addText((text) => text.setValue(this.plugin.settings.logDirectory).onChange(async (value) => {
      this.plugin.settings.logDirectory = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian8.Setting(containerEl).setName("Telegram Sync Settings").setHeading();
    new import_obsidian8.Setting(containerEl).setName("Telegram Bot Token").setDesc("Token from @BotFather.").addText((text) => text.setPlaceholder("Enter your bot token").setValue(this.plugin.settings.tgBotToken).onChange(async (value) => {
      this.plugin.settings.tgBotToken = value;
      await this.plugin.saveSettings();
      this.plugin.startPolling();
    }));
    new import_obsidian8.Setting(containerEl).setName("My Chat ID").setDesc("Whitelisted Chat ID to receive messages from.").addText((text) => text.setPlaceholder("Enter your Chat ID").setValue(this.plugin.settings.tgChatId).onChange(async (value) => {
      this.plugin.settings.tgChatId = value;
      await this.plugin.saveSettings();
      this.plugin.startPolling();
    }));
    new import_obsidian8.Setting(containerEl).setName("Polling Interval (seconds)").setDesc("How often to check for new messages.").addText((text) => text.setValue(String(this.plugin.settings.tgPollingInterval)).onChange(async (value) => {
      const num = parseInt(value);
      if (!isNaN(num) && num > 0) {
        this.plugin.settings.tgPollingInterval = num;
        await this.plugin.saveSettings();
        this.plugin.startPolling();
      }
    }));
    new import_obsidian8.Setting(containerEl).setName("Target Note Path").setDesc("Path to the Markdown file where notes will be saved (e.g. Inbox/TG-Notes.md).").addText((text) => text.setValue(this.plugin.settings.tgSavePath).onChange(async (value) => {
      this.plugin.settings.tgSavePath = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian8.Setting(containerEl).setName("Enable DeepSeek Processing").setDesc("Use AI to format and correct the incoming messages.").addToggle((toggle) => toggle.setValue(this.plugin.settings.tgAiProcessing).onChange(async (value) => {
      this.plugin.settings.tgAiProcessing = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian8.Setting(containerEl).setName("Prompt Template").setDesc("Template for AI processing. Use {{tg_message}} as placeholder.").addTextArea((text) => text.setValue(this.plugin.settings.tgPromptTemplate).onChange(async (value) => {
      this.plugin.settings.tgPromptTemplate = value;
      await this.plugin.saveSettings();
    }));
  }
};
